### Health Check
GET http://localhost:8080/api/health-check-http
Accept: application/json

###

### Register a new user
POST http://localhost:8080/api/auth/register-email
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "12345678"
}

###

### Login user (Web platform)
POST http://localhost:8080/api/auth/login-email
Content-Type: application/json
X-Platform: web

{
  "email": "test@example.com",
  "password": "12345678"
}

###

### Login user (Mobile platform)
POST http://localhost:8080/api/auth/login-email
Content-Type: application/json
X-Platform: mobile

{
  "email": "test@example.com",
  "password": "12345678"
}